development:
  adapter: postgresql
  encoding: unicode
  database: berrinche_site_development
  pool: 5
  username: tomascharad
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: berrinche_siteCRM_test
  pool: 5
  username: tomascharad
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: berrinche_site_production
  pool: 5
  username: tomascharad
  password: